Task_2_1_1
Rustam-Khamidullin/OOP pull request #12
Opened 2024-02-06 18:07 UTC by Rustam-Khamidullin

2024-02-14 04:36 UTC, BIGNIKi requested changes

2024-02-14 04:36 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/ru/nsu/khamidullin/ConsistentSolution.java
> +        for (var elem : array) {
Сделай то же самое, через stream

2024-02-14 04:36 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/ru/nsu/khamidullin/ParallelSolution.java
> +            for (int i = start; i < end; i++) {
Давай тоже через stream

2024-02-14 04:36 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/ru/nsu/khamidullin/ParallelSolution.java
> +        boolean result = false;
Можно явно не приравнивать, default значение и так false

2024-02-14 04:36 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/ru/nsu/khamidullin/ParallelSolution.java
> +    public static boolean findPrimeParallel(int[] array, int threadNumber) {
Метод надо декомпозировать - слишком перегружен.
Запуск Thread`ов - в один метод, ожидание завершения их работы - в другой

2024-02-14 04:36 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/ru/nsu/khamidullin/ParallelSolution.java
> +            throw new IllegalArgumentException("Incorrect thread number");
Такие вещи тоже стоит тестами покрывать: кто-нибудь когда-нибудь решит внести изменения в код, удалит такую проверку, а тесты не покажут, что поведение отличается от ожидаемого, появится бага, которую надо искать. А вот был бы на это дело тест, ещё во время разработки стало бы понятно, в чем дело.

2024-02-14 04:36 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/ru/nsu/khamidullin/ParallelSolution.java
> +    public static boolean findPrimeParallel(int[] array, int threadNumber) {
Все три класса ConsistentSolution, ParallelSolution, StreamSolution - решают одну и ту же задачу. Это значит, что они должны наследовать некий абстрактный класс, с абстрактным методом - find. Плюс туда же можно твой метод isPrime засунуть.

2024-02-14 04:36 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/ru/nsu/khamidullin/ParallelSolution.java
> +package ru.nsu.khamidullin;
Вынеси все классы в пакет, с говорящим названием. Классы нужно размещать по пакетам, группируя по логическим соображениям.
Если ты захочешь предоставить свой jar`ник другим пользователям, ru.nsu.khamidullin - будет не самым удачным названием для пакета, решающего задачу поиска простых чисел.

2024-02-14 10:14 UTC, BIGNIKi requested changes

2024-02-14 10:14 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/ru/nsu/khamidullin/StreamSolution.java
> +    public static boolean findPrimeStream(int[] array) {
Добавь сюда возможность настроить число Thread`ов, которые будет использовать parallelStream

2024-02-14 10:16 UTC, Rustam-Khamidullin commented on Task_2_1_1/src/main/java/ru/nsu/khamidullin/ParallelSolution.java
> +    public static boolean findPrimeParallel(int[] array, int threadNumber) {
Я хотел так сделать, но в последовательном выполнение не нужно передавать количество нитей. Поэтому непонятно какой должен быть интерфейс

2024-02-14 13:57 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/ru/nsu/khamidullin/ParallelSolution.java
> +    public static boolean findPrimeParallel(int[] array, int threadNumber) {
Не обязательно интерфейс, говорю: сделай абстрактный класс.
Например, ты хочешь сделать класс ParallelSolution:
1) наследуешь его от абстрактного класса
2) в абстрактном классе есть абстрактный метод HasPrime(int[] array) - реализуешь его в ParallelSolution
3) также в ParallelSolution делаешь конструктор, который принимает число тредов.
4) в методе HasPrime используешь число тредов, которое передали в конструктор

Получили то, что хотели: абстрактный класс есть, абстрактный метод есть, поведение разное для всех 3 реализаций.

2024-02-14 13:58 UTC, BIGNIKi commented on Task_2_1_1/src/main/java/ru/nsu/khamidullin/ParallelSolution.java
> +    public static boolean findPrimeParallel(int[] array, int threadNumber) {
Да, ты откажешься от статичных методов, зато приблизишься к соблюдению solid`ов + код будет написан на уровне абстракции

2024-02-22 05:40 UTC, BIGNIKi approved these changes

2024-02-22 05:42 UTC, merged