Task_1_1_1
Rustam-Khamidullin/OOP pull request #2
Opened 2023-09-12 17:01 UTC by Rustam-Khamidullin

2023-09-16 08:54 UTC, BIGNIKi requested changes

2023-09-16 08:54 UTC, BIGNIKi commented on Task_1_1_1/src/main/java/ru/nsu/khamidullin/Main.java
> +public class Main {
Вынеси реализацию сортировки в отдельный класс, e.g. "HeapSort". Потому что любой, кто читает код, будет ожидать в классе Main точку входа приложения, а не конкретную реализацию некоторой сущности.

2023-09-16 08:54 UTC, BIGNIKi commented on Task_1_1_1/src/main/java/ru/nsu/khamidullin/Main.java
> +    public static void main(String[] args) {
Ещё, по заданию, нужно написать bat/shell скрипт, который у тебя скомпилирует .class файлы, сгенерирует javadoc и исполнит Main класс (надо будет точку входа все-таки дополнить, вызвать там сортировку и вывести числа на консоль).

2023-09-16 08:54 UTC, BIGNIKi commented on Task_1_1_1/src/test/java/ru/nsu/khamidullin/MainTest.java
> +public class MainTest {
У тебя здесь один тест = много тестов. Это не самая лучшая практика, т.к. если у тебя один из Assert  упадет, в отчете напишут: "Упал один тест из одного". Сиди потом, разбирайся, какой именно из твоих assert`ов полетел и где в коде есть бага...
Один тест, в идеале, должен тестировать ровно один случай входных данных.
Достичь этого ты можешь следующими способами:
1) Простой способ: написать много тестовых методов, в каждом из которых проверяется уникальный случай и используется ровно один Assert. 
2) Пожалуй, самый изящный способ: использовать параметризованные тесты (это когда ты пишешь всего один тестовый метод, кормишь ему разные тестовые данные и у тебя в итоговом отчете будет написано, что тестов было столько, сколько тестовых данных ты скормил этому тесту. И если на каких-то тестовых данных тест упадет, ты непременно об этом узнаешь.). Достичь этого можно, используя аттрибут @ParameterizedTest. Почитать об этом можно здесь https://www.baeldung.com/parameterized-tests-junit-5.
В итоге у тебя получится что-то в этом духе (прикрепил скрин).
![image](https://github.com/Rustam-Khamidullin/OOP/assets/91887896/b2c93f8e-c556-47b5-9f8b-a0ebb47c23eb)

2023-09-16 08:54 UTC, BIGNIKi commented on Task_1_1_1/src/main/java/ru/nsu/khamidullin/Main.java
> +    public static int[] heapsort(int[] arr) {
Сможешь сделать так, чтобы исходный массив "arr" не модифицировался внутри метода? Чтобы возвращаемый объект и тот объект, который подаётся на вход методу, имели разные ссылки?

2023-09-23 09:20 UTC, BIGNIKi requested changes

2023-09-23 09:20 UTC, BIGNIKi commented on Task_1_1_1/src/main/java/ru/nsu/khamidullin/Main.java
> +            System.out.print(arr[i] + " ");
Давай всё-таки выведем отсортированный массив, а не исходный.

2023-09-23 09:20 UTC, BIGNIKi commented on Task_1_1_1/src/main/java/ru/nsu/khamidullin/build_and_run.bat
> +javac *.java
bat`ник всё-таки надо добить до конца и сделать рабочим.

2023-09-23 09:22 UTC, BIGNIKi commented on Task_1_1_1/src/main/java/ru/nsu/khamidullin/build_and_run.bat
> +javac *.java
У тебя, насколько я помню, java ругался на версию с которой запускаешь и с которой компилировал. Можно попробовать в path пути прописать другие.
Что-то подобное здесь на видео можно увидеть, хоть там и другую проблему решают https://www.youtube.com/watch?v=PRlxPOyjUyk&t=2s

2023-09-24 06:59 UTC, Rustam-Khamidullin commented on Task_1_1_1/src/main/java/ru/nsu/khamidullin/build_and_run.bat
> +javac *.java
Не получилось( Я уже все гайды пересмотрел.

2023-09-27 11:28 UTC, BIGNIKi commented on Task_1_1_1/src/main/java/ru/nsu/khamidullin/build_and_run.bat
> +javac *.java
Задачу тебе засчитал. А насчет bat`ника, давай на семинаре или после попробуем.

2023-10-01 07:01 UTC, BIGNIKi requested changes

2023-10-01 07:01 UTC, BIGNIKi commented on Task_1_1_1/src/main/java/ru/nsu/khamidullin/Main.java
> +public class Main {
У тебя в Main косяк. Ты же сделал реализацию heapsort таковой, что она не изменяет массив, который подали на вход. Нужно выводить тот массив, который возвращает сортировка, а не тот, который подал на вход методу.

2023-10-04 11:52 UTC, BIGNIKi approved these changes
Задачу принял

2023-10-04 11:52 UTC, BIGNIKi commented on .gitignore
> +/OOP.iml
Папку out и javadoc я бы тоже в .gitignore добавил (т.к. нет смысла их хранить в репозитории, если есть скрипт для их генерации), но это уже не принципиально.

2023-10-13 16:42 UTC, merged